BEGIN;

CREATE TABLE public."SportSeasonSubdivision" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    "sportSeasonId" bigint NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    "regularSeasonStart" date NOT NULL,
    "regularSeasonEnd" date NOT NULL,
    "postseasonStart" date,
    "postseasonEnd" date,

    CONSTRAINT "SportSeasonSubdivision_sportSeasonId_fkey"
        FOREIGN KEY ("sportSeasonId")
        REFERENCES public."SportSeason" (id)
        ON DELETE CASCADE,

    CONSTRAINT "SportSeasonSubdivision_sportSeason_code_key"
        UNIQUE ("sportSeasonId", code),

    CONSTRAINT "SportSeasonSubdivision_code_not_blank_check"
        CHECK (length(btrim(code)) > 0),

    CONSTRAINT "SportSeasonSubdivision_name_not_blank_check"
        CHECK (length(btrim(name)) > 0),

    CONSTRAINT "SportSeasonSubdivision_regular_dates_check"
        CHECK ("regularSeasonEnd" >= "regularSeasonStart"),

    CONSTRAINT "SportSeasonSubdivision_postseason_dates_paired_check"
        CHECK (("postseasonStart" IS NULL) = ("postseasonEnd" IS NULL)),

    CONSTRAINT "SportSeasonSubdivision_postseason_dates_check"
        CHECK (
            "postseasonStart" IS NULL
            OR "postseasonEnd" >= "postseasonStart"
        )
);

COMMENT ON TABLE public."SportSeasonSubdivision" IS
    'Subdivision-specific regular-season and postseason windows within a SportSeason.';

COMMENT ON COLUMN public."SportSeasonSubdivision".code IS
    'Stable subdivision identifier such as FBS or FCS.';

COMMENT ON COLUMN public."SportSeasonSubdivision"."regularSeasonStart" IS
    'Inclusive first date of the subdivision regular season.';

COMMENT ON COLUMN public."SportSeasonSubdivision"."regularSeasonEnd" IS
    'Inclusive final date of the subdivision regular season.';

COMMENT ON COLUMN public."SportSeasonSubdivision"."postseasonStart" IS
    'Inclusive first date of the subdivision postseason, when applicable.';

COMMENT ON COLUMN public."SportSeasonSubdivision"."postseasonEnd" IS
    'Inclusive final date of the subdivision postseason, when applicable.';

COMMIT;
